import { Apartment, MetricCard, Product, ServiceItem, Transaction } from "@/types";

export const heroMetrics: MetricCard[] = [
  { label: "Verified vendors", value: "1,240+", delta: "Across Redemption City and Lagos Mainland", tone: "success" },
  { label: "Average delivery", value: "28 mins", delta: "Same-community dispatch available" },
  { label: "Active bookings", value: "380", delta: "Short-lets and serviced apartments", tone: "warning" },
];

export const marketplaceProducts: Product[] = [
  {
    id: "premium-ofada-rice-50kg",
    name: "Premium Ofada Rice (50kg)",
    category: "Groceries",
    vendor: "Amina's Fashion & Farms",
    price: 42500,
    rating: 4.9,
    eta: "25 mins to Redemption City",
    location: "Redemption City",
    image: "/images/product-rice.png",
    inStock: true,
    verified: true,
    fastDelivery: true,
    highlight: "Cheapest Option",
    description: "Stone-free, locally milled and ready for homes, restaurants, and bulk family purchases.",
  },
  {
    id: "220ah-inverter-battery",
    name: "220Ah Inverter Battery",
    category: "Power & Solar",
    vendor: "Bright Grid Energy",
    price: 215000,
    rating: 4.8,
    eta: "4 hours to Lagos Mainland",
    location: "Lagos Mainland",
    image: "/images/product-power.png",
    inStock: true,
    verified: true,
    fastDelivery: false,
    description: "Reliable backup power for homes, POS stations, salons, and neighborhood stores.",
  },
  {
    id: "premium-designer-kaftan",
    name: "Premium Designer Kaftan",
    category: "Fashion",
    vendor: "Zainab Couture Hub",
    price: 32000,
    rating: 4.7,
    eta: "15 mins (in-store pickup)",
    location: "Abuja Central",
    image: "/images/product-fashion.png",
    inStock: true,
    verified: true,
    fastDelivery: true,
    description: "Tailored kaftan with premium finishing for weddings, Friday outings, and gifting.",
  },
  {
    id: "pure-red-palm-oil-5l",
    name: "Pure Red Palm Oil (5L)",
    category: "Groceries",
    vendor: "Mama Ifeanyi Foods",
    price: 8500,
    originalPrice: 9200,
    rating: 4.6,
    eta: "20 mins to Lagos Island",
    location: "Lagos Island",
    image: "/images/product-rice.png",
    inStock: true,
    verified: true,
    fastDelivery: true,
    highlight: "Cheapest Option",
    description: "Freshly processed, bright red palm oil sourced from trusted farmers and women cooperatives.",
  },
  {
    id: "portable-gas-generator",
    name: "Portable Gas Generator",
    category: "Power & Solar",
    vendor: "Mainland Tools Depot",
    price: 185000,
    rating: 4.7,
    eta: "2 days delivery",
    location: "Ikeja",
    image: "/images/product-power.png",
    inStock: true,
    verified: true,
    fastDelivery: false,
    description: "Compact generator for homes and small businesses needing dependable backup power.",
  },
  {
    id: "organic-soup-spice-kit",
    name: "Organic Soup Spice Kit",
    category: "Groceries",
    vendor: "Abuja Kitchen Basket",
    price: 12400,
    rating: 4.8,
    eta: "10 mins to Abuja Central",
    location: "Abuja Central",
    image: "/images/product-spice.png",
    inStock: true,
    verified: true,
    fastDelivery: true,
    description: "Soup spice mix with dry pepper, crayfish, iru, and kitchen-ready seasoning blends.",
  },
];

export const serviceListings: ServiceItem[] = [
  {
    id: "chidis-elite-electronics",
    name: "Elite Electrical Works",
    category: "Electrician",
    provider: "Verified Electrician",
    rate: "₦12,000 / visit",
    rating: 4.9,
    location: "Mowe, Ogun State",
    image: "/images/service-electrician.svg",
    summary: "Certified master electrician for home wiring, solar setup, and urgent fault tracing.",
  },
  {
    id: "victory-academic-prep",
    name: "Academic Success Prep",
    category: "Tutor",
    provider: "Verified Tutor",
    rate: "₦8,000 / class",
    rating: 5,
    location: "Redemption Camp",
    image: "/images/service-tutor.svg",
    summary: "Trusted WAEC, JAMB, and coding tutor for students, teens, and busy parents.",
  },
  {
    id: "tundes-flow-systems",
    name: "Flow Systems Pro",
    category: "Plumber",
    provider: "Verified Plumber",
    rate: "₦15,000 / fix",
    rating: 4.8,
    location: "Ikeja GRA",
    image: "/images/service-plumber.svg",
    summary: "Modern plumbing support for homes, estates, shops, boreholes, and smart tap installation.",
  },
];

export const apartmentListings: Apartment[] = [
  {
    id: "the-glass-house-lekki-phase-1",
    name: "The Glass House, Lekki Phase 1",
    zone: "Lekki Phase 1, Lagos",
    nightlyRate: 125000,
    rooms: "3 beds • serviced stay",
    host: "Verified Host",
    badge: "Featured Stay",
    image: "/images/apartment-premium.svg",
    summary: "Premium short-let with reliable power, security, fast Wi-Fi, and a clean modern finish.",
  },
  {
    id: "emerald-suite-2-bed",
    name: "The Emerald Suite • 2-Bed",
    zone: "Redemption City Gate",
    nightlyRate: 75000,
    rooms: "2 beds • 24/7 power",
    host: "Oluwaseun",
    image: "/images/apartment-suite.svg",
    summary: "Family-friendly apartment near camp gates, suitable for conference stays and weekend rest.",
  },
  {
    id: "savannah-studio-executive",
    name: "Savannah Studio • Executive",
    zone: "Camp Area",
    nightlyRate: 45000,
    rooms: "Studio • executive",
    host: "Adebola",
    image: "/images/apartment-studio.svg",
    summary: "Quiet studio for students, business travelers, and short stays around Redemption Camp.",
  },
];

export const walletTransactions: Transaction[] = [
  { id: "txn-001", title: "Escrow release", category: "Marketplace order", amount: "+₦24,500", status: "Completed", timestamp: "14 May • 2:20 PM" },
  { id: "txn-002", title: "Apartment booking hold", category: "Short-let payment", amount: "-₦45,000", status: "Held", timestamp: "14 May • 9:10 AM" },
  { id: "txn-003", title: "Rider payout", category: "Delivery earnings", amount: "+₦12,450", status: "Processing", timestamp: "13 May • 6:40 PM" },
];

export const dashboardStats: Record<string, MetricCard[]> = {
  customer: [
    { label: "Wallet balance", value: "₦128,490", delta: "2 deliveries active", tone: "success" },
    { label: "Orders this month", value: "18", delta: "Most from local groceries" },
    { label: "Saved this week", value: "₦6,200", delta: "Using cheapest vendor compare", tone: "warning" },
  ],
  vendor: [
    { label: "Total sales", value: "₦4,250,000", delta: "+12.5% this week", tone: "success" },
    { label: "New orders", value: "124", delta: "8 need dispatch today", tone: "warning" },
    { label: "Active products", value: "42", delta: "2 low stock items" },
  ],
  inventory: [
    { label: "Items in stock", value: "420", delta: "Across store shelves and back room" },
    { label: "Low stock alerts", value: "11", delta: "Palm oil, detergents, snacks", tone: "warning" },
    { label: "Fast movers", value: "26", delta: "Driven by groceries and power items", tone: "success" },
  ],
  logistics: [
    { label: "Today's earnings", value: "₦12,450", delta: "8 completed trips", tone: "success" },
    { label: "Assigned deliveries", value: "3", delta: "1 active right now" },
    { label: "Rider rating", value: "4.92", delta: "Top 5% in Redemption City", tone: "warning" },
  ],
  "tenant-admin": [
    { label: "Pending approvals", value: "24", delta: "Vendors and service providers" },
    { label: "Delivery issues", value: "6", delta: "2 delayed, 4 resolved today", tone: "warning" },
    { label: "Community GMV", value: "₦18.4M", delta: "This month", tone: "success" },
  ],
  "super-admin": [
    { label: "Live tenants", value: "12", delta: "Campuses, estates, smart districts" },
    { label: "Platform revenue", value: "₦82.3M", delta: "Across all communities", tone: "success" },
    { label: "Open disputes", value: "9", delta: "All under review", tone: "warning" },
  ],
  host: [
    { label: "Monthly bookings", value: "27", delta: "10 upcoming check-ins", tone: "success" },
    { label: "Occupancy rate", value: "81%", delta: "Strong weekend demand" },
    { label: "Host earnings", value: "₦1,280,000", delta: "Available for payout", tone: "warning" },
  ],
  "service-provider": [
    { label: "Bookings today", value: "6", delta: "3 confirmed, 3 pending", tone: "success" },
    { label: "Average rating", value: "4.9", delta: "Trusted by repeat customers" },
    { label: "This week earnings", value: "₦86,000", delta: "Across home visits", tone: "warning" },
  ],
  wallet: [
    { label: "Available balance", value: "â‚¦2,450,000", delta: "Wallet is active", tone: "success" },
    { label: "Escrow hold", value: "â‚¦128,400", delta: "3 orders in progress" },
    { label: "This month", value: "+â‚¦450k", delta: "Across commerce and bookings", tone: "warning" },
  ],
};
